=== Mechachleopteryx/JavaScriptSesh/public_html/xmltest/mdc2.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    An extensible DTD specification of for hieroglyphic
    manuel de codage documents.

    In general, it will be best for implementations to use non validating
    systems (to deal with extensions of the format).

    Namespace for MDC2 is supposed to be ...

    The general principle of this new system is to have a relatively loose 
    syntax. That is, most elements can occur in many different places.

    Some indications given by the document (as page size) are just that... indications.
    Implementations can choose to bypass them. For instance, page size can be ignored
    when quoting part of a text. Same thing for main text orientation.
    
    
-->

<!--
    TODO define vocabulary identification data
    PUBLIC ID  : -//vendor//vocabulary//EN
    SYSTEM ID  : http://server/path/__NAME__
-->

<!--
    Generic attributes. 
    Shared by all elements.

    id : a unique (and numerical) ID for this element.
    
-->

<!ENTITY % genAttr "
    id CDATA
">

<!-- Extension point : add any custom constructs here... (add a "|" at the beginning) -->

<!ENTITY % extContent "">

<!ENTITY %  content "(q|s%extContent;)*">

<!-- 
    MDC elements contain hieroglyphic text as a sequence of 
    more or less any kind of groups.
-->

<!ELEMENT mdc2 (%content;)>

<!-- Extension point : add any custom constructs here... -->

<!ELEMENT content (q|ANY)>

<!ELEMENT q (v*)>

<!ELEMENT v (%content;)>

<!ELEMENT s (#PCDATA)>

=== Mechachleopteryx/JavaScriptSesh/public_html/xmltest/demoMDC2a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mdc2 SYSTEM 'mdc2.dtd'>
<mdc2>
    <s>i</s>
    <s>w</s>
    <q>
        <v>
            <s>r</s>
            <s>a</s>
        </v>
    </q>
    <s>ra</s>
    <s>m</s>
    <q>
        <v>
              
            <s>p</s>
            <s>t</s>
        </v>
        <v>
            <s>pt</s>                
        </v>
    </q>
</mdc2>
